name: CI/CD
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '25 10 * * *'
jobs:
  build_and_push_container:
    name: Build & push container
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: echo ${{secrets.GITHUB_TOKEN}} | podman login -u ${{github.actor}} --password-stdin ghcr.io
      - name: Build
        run: podman build -t localhost/calcite .
      - name: Tag & push
        if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
        run: |
          set -euxo pipefail
          for tag in latest a9.5; do
            podman tag localhost/calcite ghcr.io/calciteauthors/calcite:${tag}
            podman push ghcr.io/calciteauthors/calcite:${tag}
          done
  build_and_upload_iso:
    if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    name: Build & upload ISO
    needs: build_and_push_container
    runs-on: ubuntu-24.04
    container: fedora:41
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dnf install -y --allowerasing lorax util-linux skopeo curl
      - name: Download container
        run: skopeo copy docker://ghcr.io/calciteauthors/calcite:latest oci:container
      - name: Download AlmaLinux
        run: curl -Ls -o almalinux.iso https://nyc.mirrors.clouvider.net/almalinux/9.5/BaseOS/x86_64/os/images/boot.iso
      - name: Run mkksiso
        run: mkksiso -a container ks.cfg almalinux.iso calcite.iso
      - uses: actions/upload-artifact@v4
        name: Upload
        with:
          name: iso
          path: calcite.iso
